default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotwire_demo_development
  username: postgres
  password: root

test:
  <<: *default
  database: hotwire_demo_test
  username: postgres
  password: root

production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cable:
  <<: *production
  database: myapp_cable_production
